Kick_reason: "\xA74\u65E0\u6CD5\u8FDE\u63A5\u5230\u670D\u52A1\u5668\uFF0C\u56E0\u4E3A\
  \u4F60\u4E0D\u5728MTS\u767D\u540D\u5355\u5185\uFF1A\xA76\u8BF7\u8054\u7CFBGamerNoTitle\u628A\
  \u4F60\u52A0\u5165\u767D\u540D\u5355\uFF0CEFS\u670D\u52A1\u5668\u73A9\u5BB6\u8BF7\
  \u79C1\u804AGamerNoTitle;\xA7bGamerNoTitle\u7684\u8054\u7CFB\u65B9\u5F0F\uFF1A\u53D1\
  \u90AE\u4EF6\u5230\xA7d\xA7ladmin@bili33.top\xA7r\xA7b\u6216\u8005\xA7d\xA7lQQ3559869084"
Whitelist_IP: []
Whitelist_player: [bot_PCRC, slcy, NG, Yukiyuki_mafu, Yang_Shu_, mafumafu_Yuki, cai_niao_te_cai_,
  MI_rice.json, eagleworld, GamerNoTitle, UBIthepotato, dull_eye, YunJi_O, qwer, blacorz,
  bot_PCRC_Ali, bot_PCRC_local, hzflo, Guo0zi, xun_xi, Mach_R2006, 2x_ercha, bai_tian_1]
Whitelist_status: On
admin: [GamerNoTitle, UBIthepotato]
ip_whitelist_status: Off
